# Generated by Django 4.2.20 on 2026-09-13 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_test', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ'), ('behavioral', 'Behavioral'), ('technical', 'Technical')], max_length=20)),
                ('difficultiy', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(choices=[('easy', 'Easy'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('jd', models.ForeignKey(blank=True, db_column='jd_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.jobdescription')),
                ('resume', models.ForeignKey(blank=True, db_column='resume_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
