# Generated by Django 4.2.20 on 2026-09-13 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='jd',
        ),
        migrations.AddField(
            model_name='questions',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.CreateModel(
            name='WeakArea',
            fields=[
                ('weak_area_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=100)),
                ('performance_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'weak_areas',
            },
        ),
        migrations.AddConstraint(
            model_name='weakarea',
            constraint=models.CheckConstraint(check=models.Q(('performance_score__gte', 0), ('performance_score__lte', 100)), name='weak_area_performance_score_range'),
        ),
    ]
