# Generated by Django 4.2.20 on 2026-09-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_questions_jd_questions_user_weakarea_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='difficultiy',
            new_name='difficulty',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='question_test',
            new_name='question_text',
        ),
    ]
