# Generated by Django 4.2.20 on 2026-09-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_rename_difficultiy_questions_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='difficulty',
        ),
        migrations.AlterField(
            model_name='questions',
            name='correct_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
