# Generated by Django 4.2.20 on 2026-09-18 14:31

from django.db import migrations, models
import django.db.models.deletion
import professionalContent.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_profile'),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('export_id', models.AutoField(primary_key=True, serialize=False)),
                ('export_type', models.CharField(choices=[('resume', 'Improved Resume'), ('linkedin', 'LinkedIn Summary'), ('cover_letter', 'Cover Letter')], max_length=20)),
                ('file_path', models.FileField(upload_to=professionalContent.models.export_file_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(db_column='resume_id', on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='resume.resume')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='accounts.user')),
            ],
            options={
                'db_table': 'exports',
                'ordering': ['-created_at'],
            },
        ),
    ]
