# Generated by Django 4.2.20 on 2026-09-20 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
        ('professionalContent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='export',
            name='resume',
            field=models.ForeignKey(blank=True, db_column='resume_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='resume.resume'),
        ),
    ]
