# Generated by Django 4.2.20 on 2026-10-10 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('general', 'General'), ('resume', 'Resume tools'), ('ats', 'ATS score'), ('roadmap', 'Roadmap'), ('interview', 'Interview prep'), ('idea', 'Feature idea'), ('bug', 'Something is broken')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='feedback_rating_range'),
        ),
    ]
