# Generated by Django 4.2.20 on 2026-09-07 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resume_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX')], max_length=10)),
                ('parsed_text', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='accounts.user')),
            ],
            options={
                'db_table': 'resume',
            },
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('version_id', models.AutoField(primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('content_snapshot', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('versions', models.ForeignKey(db_column='resume_id', on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
            options={
                'db_table': 'resume_version',
                'ordering': ['version_number'],
            },
        ),
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('ats_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grammar_issues', models.JSONField(blank=True, null=True)),
                ('passive_voice_flags', models.JSONField(blank=True, null=True)),
                ('missing_section', models.JSONField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('analyses', models.ForeignKey(db_column='version_id', on_delete=django.db.models.deletion.CASCADE, to='resume.resumeversion')),
            ],
            options={
                'db_table': 'resume_analysis',
            },
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('jd_id', models.AutoField(primary_key=True, serialize=False)),
                ('jd_text', models.TextField()),
                ('target_role', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_descriptions', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'job_descriptions',
            },
        ),
        migrations.CreateModel(
            name='JDMatchResult',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('missing_keywords', models.JSONField(blank=True, null=True)),
                ('search_type', models.CharField(choices=[('with_resume', 'With Resume'), ('without_resume', 'Without Resume')], max_length=20)),
                ('required_skills', models.JSONField(blank=True, null=True)),
                ('jd', models.ForeignKey(db_column='jd_id', on_delete=django.db.models.deletion.CASCADE, related_name='jd_matches', to='resume.jobdescription')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='jd_matches', to='accounts.user')),
                ('version', models.ForeignKey(blank=True, db_column='version_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jd_matches', to='resume.resumeversion')),
            ],
            options={
                'db_table': 'jd_matches',
            },
        ),
        migrations.AddConstraint(
            model_name='resumeanalysis',
            constraint=models.CheckConstraint(check=models.Q(('ats_score__gte', 0), ('ats_score__lte', 100)), name='resume_analysis_ats_score_range'),
        ),
        migrations.AddConstraint(
            model_name='jdmatchresult',
            constraint=models.CheckConstraint(check=models.Q(('match_percentage__isnull', True), models.Q(('match_percentage__gte', 0), ('match_percentage__lte', 100)), _connector='OR'), name='jd_match_results_percentage_range'),
        ),
    ]
